---

- yum: 
    name: puppet-agent
    state: present
  when: ansible_distribution == 'CentOS'

- apt:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
